on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Sonar
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - run: npm ci
      - run: npm run build
      - run: npm test -- --watchAll=false

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: /opt/sonar-scanner/.sonar/cache
          key: sonar-cache
          restore-keys: sonar-cache
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
